import { NextRequest, NextResponse } from "next/server";

// ── Known scam wallet addresses (famous cases) ────────────────────────────────
const KNOWN_SCAM_WALLETS = new Set([
    "0x7f268357a8c2552623316e2562d90e642bb538e5",
    "0x3f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be",
    "0xd882cfc20f52f2599d84b8e8d58c7fb62cfe344b",
    "0xa7efae728d369157a3643bbd1d399e3e7b5bfbde",
    "0x564286362092d8e7936f0549571a803b203aced4",
    "1FeexV6bAHb8ybZjqQMjJrcCrHGW9sb6uF",
    "1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp",
    "bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh",
    "TKFLVuMtTx9xHUjkCnEfmQAX8GqAj5mHHA",
]);

// ── Suspicious TLDs commonly used in scam domains ──────────────────────────────
const SUSPICIOUS_TLDS = [
    ".xyz", ".top", ".click", ".tk", ".ml", ".ga", ".cf", ".gq",
    ".rest", ".live", ".info", ".biz", ".online", ".site", ".website",
    ".loan", ".win", ".stream", ".download", ".accountant", ".trade",
    ".science", ".date", ".faith", ".review", ".party", ".gdn",
];

// ── Crypto platform impersonation patterns ────────────────────────────────────
const IMPERSONATION_PATTERNS = [
    /binance[-.]?(official|secure|pro|verified|support)/i,
    /coinbase[-.]?(official|secure|pro|support|wallet)/i,
    /crypto[-.]?(official|secure|wallet|fund|profit)/i,
    /bitcoin[-.]?(official|secure|wallet|fund|profit|invest)/i,
    /eth[-.]?(official|secure|wallet|fund|profit|invest)/i,
    /metamask[-.]?(official|secure|support|help|wallet)/i,
    /trust[-.]?(wallet|official|secure|support)/i,
    /kraken[-.]?(official|secure|pro|support)/i,
    /ftx[-.]?(official|secure|pro|recovery)/i,
    /recovery[-.]?(crypto|bitcoin|eth|fund|wallet)/i,
    /claim[-.]?(crypto|bitcoin|eth|reward|airdrop)/i,
    /airdrop[-.]?(crypto|bitcoin|eth|official)/i,
    /double[-.]?(bitcoin|eth|crypto|your)/i,
    /profit[-.]?(crypto|bitcoin|eth|daily|guaranteed)/i,
    /invest[-.]?(crypto|bitcoin|eth|guaranteed|profit)/i,
];

// ── High-risk keywords in domain names ───────────────────────────────────────
const SCAM_KEYWORDS = [
    "freecrypto", "getbtc", "doubleyour", "cryptogain", "bitcoinprofit",
    "ethgiveaway", "cryptoreward", "bitcoinreward", "freemoney",
    "earnbtc", "earneth", "cryptoearn", "passiveincome", "getrich",
    "cryptosecret", "elonmusk", "musk", "giveaway", "free-btc",
    "free-eth", "investment-return", "guaranteed-profit",
];

// ── Helpers ───────────────────────────────────────────────────────────────────
function isEthAddress(s: string) {
    return /^0x[0-9a-fA-F]{40}$/.test(s.trim());
}
function isBtcAddress(s: string) {
    return /^(1|3)[a-zA-HJ-NP-Z0-9]{25,34}$|^bc1[a-z0-9]{39,59}$/.test(s.trim());
}
function isTronAddress(s: string) {
    return /^T[a-zA-Z0-9]{33}$/.test(s.trim());
}

function detectInputType(input: string): "wallet" | "url" | "unknown" {
    const s = input.trim();
    if (isEthAddress(s) || isBtcAddress(s) || isTronAddress(s)) return "wallet";
    try {
        const u = new URL(s.startsWith("http") ? s : `https://${s}`);
        if (u.hostname.includes(".")) return "url";
    } catch {}
    return "unknown";
}

// ── Wallet checker ────────────────────────────────────────────────────────────
function checkWallet(address: string): { score: number; flags: string[]; info: string[] } {
    const flags: string[] = [];
    const info: string[] = [];
    let score = 0;

    const lower = address.toLowerCase();

    if (KNOWN_SCAM_WALLETS.has(lower)) {
        flags.push("⚠️ This address appears in our scam wallet database");
        flags.push("⚠️ Transactions to this address have been reported as fraudulent");
        score += 90;
    }

    if (isEthAddress(address)) {
        info.push("✓ Valid Ethereum (ERC-20) address format");
    } else if (isBtcAddress(address)) {
        info.push("✓ Valid Bitcoin address format");
    } else if (isTronAddress(address)) {
        info.push("✓ Valid TRON (TRC-20) address format");
        info.push("Note: TRON addresses are heavily used in USDT scam transfers");
        score += 10;
    } else {
        flags.push("⚠️ Non-standard wallet address format — could be from a fake platform");
        score += 40;
    }

    // Entropy check — unusually simple addresses are sometimes used in scams
    const uniqueChars = new Set(address.replace("0x", "").split("")).size;
    if (uniqueChars < 8) {
        flags.push("⚠️ Unusually low entropy in address — may be generated by a fraudulent platform");
        score += 20;
    }

    if (score === 0) {
        info.push("No known fraud flags found for this address in our database");
        info.push("Note: Absence of flags does not guarantee a wallet is safe");
    }

    return { score: Math.min(score, 100), flags, info };
}

// ── URL checker ───────────────────────────────────────────────────────────────
function checkUrl(rawUrl: string): { score: number; flags: string[]; info: string[] } {
    const flags: string[] = [];
    const info: string[] = [];
    let score = 0;

    let hostname = "";
    let pathname = "";
    try {
        const u = new URL(rawUrl.startsWith("http") ? rawUrl : `https://${rawUrl}`);
        hostname = u.hostname.toLowerCase();
        pathname = u.pathname;
    } catch {
        return { score: 60, flags: ["⚠️ Could not parse URL — may be malformed"], info: [] };
    }

    // TLD check
    const matchedTld = SUSPICIOUS_TLDS.find((t) => hostname.endsWith(t));
    if (matchedTld) {
        flags.push(`⚠️ High-risk top-level domain detected: "${matchedTld}" — frequently used in scam sites`);
        score += 30;
    }

    // Impersonation
    for (const pattern of IMPERSONATION_PATTERNS) {
        if (pattern.test(hostname)) {
            flags.push("🚨 Domain appears to impersonate a legitimate crypto exchange or wallet service");
            score += 50;
            break;
        }
    }

    // Scam keywords
    const matchedKw = SCAM_KEYWORDS.find((k) => hostname.replace(/[-_.]/g, "").includes(k));
    if (matchedKw) {
        flags.push(`🚨 High-risk keyword found in domain: "${matchedKw}" — commonly used in investment scams`);
        score += 40;
    }

    // IP address as domain
    if (/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(hostname)) {
        flags.push("🚨 Domain is a raw IP address — legitimate services never use IP addresses as their main URL");
        score += 60;
    }

    // Excessive hyphens
    const hyphens = (hostname.match(/-/g) || []).length;
    if (hyphens >= 3) {
        flags.push("⚠️ Domain contains many hyphens — a common technique used to create fake lookalike domains");
        score += 20;
    }

    // Very long subdomain chain
    const parts = hostname.split(".");
    if (parts.length > 4) {
        flags.push("⚠️ Unusually deep subdomain structure — often used to fake legitimacy (e.g. coinbase.com.fake-site.xyz)");
        score += 25;
    }

    // Crypto words in domain
    const cryptoTerms = ["bitcoin", "btc", "ethereum", "eth", "crypto", "wallet", "defi", "nft", "coin", "token"];
    const hasCryptoTerm = cryptoTerms.some((t) => hostname.includes(t));
    if (hasCryptoTerm && score > 0) {
        flags.push("⚠️ Crypto-related terms in domain combined with other risk signals — elevated fraud probability");
        score += 10;
    }

    // No https
    if (!rawUrl.startsWith("https://") && !rawUrl.startsWith("http://")) {
        info.push("Assuming HTTPS — always check that a site uses HTTPS before sending funds");
    }

    if (score === 0) {
        info.push("No obvious risk patterns detected in this URL");
        info.push("Note: Advanced phishing sites can bypass basic pattern checks — always verify via official channels");
        score = 5;
    }

    if (flags.length === 0 && score < 30) {
        info.push(`Domain "${hostname}" passed basic pattern analysis`);
    }

    return { score: Math.min(score, 100), flags, info };
}

// ── Risk level ────────────────────────────────────────────────────────────────
function getRiskLevel(score: number): { level: string; color: string; advice: string } {
    if (score >= 70) return {
        level: "HIGH RISK",
        color: "red",
        advice: "Do NOT send funds to this address/site. Multiple serious fraud indicators detected. If you have already sent funds, contact us immediately for a recovery consultation.",
    };
    if (score >= 40) return {
        level: "SUSPICIOUS",
        color: "orange",
        advice: "Exercise extreme caution. This address/site shows warning signs associated with scam operations. Verify through official channels before proceeding.",
    };
    if (score >= 15) return {
        level: "LOW RISK",
        color: "yellow",
        advice: "No major red flags found, but always verify the source independently. Scammers can use clean addresses/domains initially.",
    };
    return {
        level: "APPEARS SAFE",
        color: "green",
        advice: "No known fraud indicators detected. Continue to exercise caution — our database is updated regularly but cannot guarantee safety.",
    };
}

// ── Route handler ─────────────────────────────────────────────────────────────
export async function POST(req: NextRequest) {
    try {
        const { input } = await req.json();
        if (!input || typeof input !== "string") {
            return NextResponse.json({ error: "Input is required" }, { status: 400 });
        }

        const trimmed = input.trim();
        if (trimmed.length < 5) {
            return NextResponse.json({ error: "Input too short" }, { status: 400 });
        }

        const type = detectInputType(trimmed);
        let result: { score: number; flags: string[]; info: string[] };

        if (type === "wallet") {
            result = checkWallet(trimmed);
        } else if (type === "url") {
            result = checkUrl(trimmed);
        } else {
            // Try as URL anyway
            result = checkUrl(trimmed);
        }

        const risk = getRiskLevel(result.score);

        return NextResponse.json({
            input: trimmed,
            type,
            score: result.score,
            risk,
            flags: result.flags,
            info: result.info,
            checkedAt: new Date().toISOString(),
        });
    } catch {
        return NextResponse.json({ error: "Check failed" }, { status: 500 });
    }
}
